### ISSUE TITLE
Duplicate entries

### ISSUE THREAD

**Issue by biau** [doudz/homeassistant-zigate#103]
I have an issu with xiaomi temp sensor displaying as duplicate in zigate admin page:
![image](https://user-images.githubusercontent.com/5954351/75110037-2dc8be80-5629-11ea-9c81-7c88439f3ccc.png)
I have tried to remove/delete both of them from the device page and nothing happens.
Any idea how I can remove the first and wrong entry ?

**Comment by doudz** [comment]
Did you try the delete button ?

**Comment by doudz** [comment]
the delete button should works since it force the deletion

**Comment by biau** [comment]
Ok, but the url generated is like this:
/zigateproxy?q=%2Fapi%2Fremove%2F2d5d&_=1582544629.1893158?force=true

the ? in front of force is correct (I've try replacing it with & but my entity is still there)

**Comment by doudz** [comment]
oh.. that's the reason, try this url 
`/zigateproxy?q=%2Fapi%2Fremove%2F2d5d%3Fforce%3Dtrue&_=1582544629.1893158`

**Comment by biau** [comment]
it works, thanks
