### ISSUE TITLE
Installation impossible?

### ISSUE THREAD

**Issue by ArthurMalet** [doudz/homeassistant-zigate#110]
Bonjour,

Malgré beaucoup de temps passé a essayer d'installer le plugin, je suis forcé de reconnaitre que je n'y arrive pas... 
Je suis sur un RPi 4, et j'ai installé homeassistant depuis l'image disponible sur le site être adapté au RPi 4.

Le premier soucis survient sur l'emplacement de mon fichier configuration.yaml: Alors que chez certains utilisateurs, il semble se trouver dans home/.home/.homeassistant, chez moi il se situe simplement dans /config/. 
J'ai donc crée le dossier custom_components/zigate/ et copié les fichiers du repo. 

Mon fichier config à été édité comme suit: 
zigate:
  gpio: true

Mais lorsque malheureusement HA me renvoie l'erreur suivante: 

> The following integrations and platforms could not be set up:
> 
> zigate 

Un coup d'oeil vers les logs et j'ai les erreurs suivantes: 
- Setup failed for zigate: Integration not found.
- Error loading custom_components.zigate. Make sure all dependencies are installed
- ModuleNotFoundError: No module named 'zigate'

Ce n'est pas dans mes habitudes de demander de l'aide rapidement mais là je suis forcé de reconnaitre de que bloque complet...

Merci à tous pour votre aide,

Arthur

**Comment by disquette38** [comment]
Bonjour doudz et toute la communauté,
Je suis dans le même cas @ArthurMalet, impossible d'installer ma PiZiGate sur RPI4 Installation avec l'image hassos_rpi4-3.13.img (32 Bits) en les fichiers du repo sont dans    /config/custom_components/zigate, comme dans les préconisations, rajouté aussi dans la partition boot/config.txt `enable_uart=1` mais la PiZiGate n'est pas connectée sur /dev/ttyAMA0

![Screenshot_373](https://user-images.githubusercontent.com/16446911/82928216-390dec00-9f82-11ea-940c-a177071fc118.png)

Merci de votre aide.

**Comment by doudz** [comment]
@ArthurMalet je pense que le dossier Zigate n'est pas au bon endroit (à vérifier) ou alors il est incomplet, il manque des fichiers.
Je recommande l'installation en utilisant HACS

**Comment by doudz** [comment]
@disquette38 il faut que je refasse un essai sur un rpi4 mais sur un rpi3 il fallait aussi désactiver ou configurer différemment le bluetooth sinon le bluetooth utilise le même port et il y a conflit

dtoverlay=pi3-miniuart-bt
enable_uart=1

**Comment by disquette38** [comment]
@doudz ,
J'ai essayé **sans la désactivation du bluetooth**  avec domoticz sur le RPI4 **c'est OK** ! ([https://zigate.fr/documentation/compatibilite-raspberry-pi-4-b/](url)
Dans le doute j'ai fais la manip de la désactivation du bluetooth pour HA c'est idem **NON OK**

Depuis l'image hassos je ne suis pas sur que la partition boot soit bien pris en compte , surtout que la partition n'est plus vue quand HA tourne.
J'attends ton retour, merci

**Comment by vini59fr** [comment]
Hello
@doudz , exactement le meme probleme que @disquette38 avec le meme panneau d'Admin . (J'ai pourtant installé Zigate via HACS)

**Comment by vini59fr** [comment]
Hello

J'ai desactivé le BT (et Wifi) dans le config.txt en rajoutant les lignes suivantes : 
dtoverlay=disable-bt
dtoverlay=disable-wifi

Le BT est bien desactivé (mes capteurs BT ne remontent plus rien) mais mon PiZigate ne remonte pas pour autant :(

**Comment by vini59fr** [comment]
j'ai fini par réussir ....
j'ai juste rajouter dans configuration.yaml :
  port: /dev/ttyAMA0

et là ca fonctionne bien, mais je n'ai plus le BT sur le Pi du coup :(

**Comment by disquette38** [comment]
J'essaye ....

**Comment by disquette38** [comment]
Effectivement ça fonctionne :) , par contre dans les log's j'ai un message d'erreur 

`Please report issue to the custom component author for zigate doing I/O at custom_components/zigate/__init__.py, line 784: r = requests.get('http://localhost:9998'+request.query.get('q', '/'), headers=headers)`

**Comment by doudz** [comment]
J'ai (enfin) fait le test sur mon Rpi 4 2G
- Installation de hassio sur la sd
- Ajout de enable_uart=1 dans config.txt sur la partition boot (c'est obligatoire sinon ça ne fonctionne pas)
- Démarrage, ajout du composant zigate (je passe le détail)
- dans configuration.yaml :
```
zigate:
  gpio: true
  port: /dev/ttyS0
```
- Redémarrage de home assistant
- et voilà !

On note qu'il n'est pas nécessaire de désactiver le bluetooth
On note également qu'il est nécessaire de spécifier le port zigate, la détection automatique ne fonctionne pas
Il est possible de vérifier les ports dispo dans Supervisor => System => Hardware
![image](https://user-images.githubusercontent.com/1262548/83322934-91cbd600-a25b-11ea-8e23-0009689f9f32.png)

**Comment by doudz** [comment]
> Effectivement ça fonctionne :) , par contre dans les log's j'ai un message d'erreur
> 
> `Please report issue to the custom component author for zigate doing I/O at custom_components/zigate/__init__.py, line 784: r = requests.get('http://localhost:9998'+request.query.get('q', '/'), headers=headers)`

Ce message d'erreur peut être ignorer pour le moment, je corrigerai ça prochainement

**Comment by vini59fr** [comment]
> J'ai (enfin) fait le test sur mon Rpi 4 2G
> 
> * Installation de hassio sur la sd (https://www.home-assistant.io/hassio/)
> * Ajout de enable_uart=1 dans config.txt sur la partition boot (c'est obligatoire sinon ça ne fonctionne pas)
> * Démarrage, ajout du composant zigate (je passe le détail)
> * dans configuration.yaml :
> 
> ```
> zigate:
>   gpio: true
>   port: /dev/ttyS0
> ```
> 
> * Redémarrage de home assistant
> * et voilà !
> 
> On note qu'il n'est pas nécessaire de désactiver le bluetooth
> On note également qu'il est nécessaire de spécifier le port zigate, la détection automatique ne fonctionne pas
> Il est possible de vérifier les ports dispo dans Supervisor => System => Hardware
> ![image](https://user-images.githubusercontent.com/1262548/83322934-91cbd600-a25b-11ea-8e23-0009689f9f32.png)

Hello @doudz 

Y'a du bon et du pas bon :D 
Effectivement, en suivant ce modop (sur le ttyS0), le Pizigate fonctionne sans désactiver le BT dans le config.txt.
MAIS le BT ne fonctionne plus quand même ....  j'ai 4 capteurs de T° en BT qui ne remontent plus les infos dans mon HA :/

**Comment by doudz** [comment]
le bluetooth est bien sur /dev/ttyAMA0 ?

**Comment by vini59fr** [comment]
Je peux voir ca où ?
J'ai une install standard de HA, je n'ai rien modifié là dessus

**Comment by doudz** [comment]
@vini59fr tu utilises quelle intégration?

**Comment by vini59fr** [comment]
@doudz 
Home Assistant 0.110.4  sur RPi4 B+ 2Go

![2020-05-30 16_35_26-Window](https://user-images.githubusercontent.com/65531566/83331032-a9bf4c00-a293-11ea-927e-6c1cb9cee703.png)

le Pizigate a été mis à jour par le service zigate.upgrade_firmware

**Comment by doudz** [comment]
Ok donc Zigate fonctionne parfaitement.
Je voulais dire pour le bluetooth, c'est quelle intégration ?

**Comment by vini59fr** [comment]
pour mes capteurs BT, j'utilise : Xiaomi passive BLE monitor sensor platform (dans HACS)

J'ai regardé, mais rien n'est parametrable pour le BT (geré en interne par HA je suppose)

**Comment by doudz** [comment]
A priori on peut spécifier l'adaptateur à utiliser https://www.home-assistant.io/integrations/mitemp_bt/

**Comment by vini59fr** [comment]
> A priori on peut spécifier l'adaptateur à utiliser https://www.home-assistant.io/integrations/mitemp_bt/

@doudz effectivement j'ai vu l'option, mais rien n'y fait
j'ouvre une issue sur cette integration ;)

merci

**Comment by vini59fr** [comment]
@doudz 

pour info, tout fonctionne enfin. J'ai juste relancé mon Pi sans le Pizigate. Puis remis le Pizigate et là j'ai les capteurs BT ET le pizigate qui fonctionnent en meme temps :D 

je ne sais pas trop ce qu'il s'est passé ni pourquoi ca fonctionne, mais c'est tant mieux ;)

**Comment by Joh10** [comment]
Bonjour, 
Je suis entrain de passer de Jeedom vers HASS sauf que je n'arrive pas à connecter ma Zigate, j'ai bien tout suivi mais elle n'est jamais connectée. Sur Jeedom tout fonctionne depuis 2 ans.
![image](https://user-images.githubusercontent.com/10811016/94858421-4efd5300-0433-11eb-93a7-8ee06eeca3a6.png)

Par contre je n'utilise pas de Raspberry mais un NUC avec une VM Hass, peut-être que c'est à ce niveau que ça coince ? Faut-il configurer quelque chose sur la VM ?

Merci pour votre aide

**Comment by doudz** [comment]
Quel est le type de zigate ?
je vois "GPIO" donc j'imagine une pizigate mais le port /dev/ttyUSB0 indique une zigate USB ou DIN

**Comment by Joh10** [comment]
Non c'est une zigate USB pardon, j'ai retiré le GPIO après la capture d'écran

**Comment by doudz** [comment]
@Joh10 idéalement il faudrait ouvrir un nouvel issue et poster le log en mode debug pour comprendre ce qu'il se passe
