### ISSUE TITLE
Error zigate.yaml

### ISSUE THREAD

**Issue by iron91770** [doudz/homeassistant-zigate#111]
Hello,

since the version of Hassio 0.107.5, I have an error on the zigate.yaml file.

Could you help me solve the problem?

This is the latest version of the file

Error loading /config/configuration.yaml: mapping values are not allowed here
  in "/config/packages/zigate.yaml", line 114, column 71

I thank you in advance

**Comment by iron91770** [comment]
This problem has trouble with 0.170 HA release due to Groups changes

**Comment by doudz** [comment]
I suggest you to upgrade, since the problem has already been fixed
and there's no line 114 in the current file

**Comment by iron91770** [comment]
sorry error copy/paste
