### ISSUE TITLE
Aide pour un interrupteur 2 voies

### ISSUE THREAD

**Issue by letroll** [doudz/homeassistant-zigate#130]
Bonjour est-ce que quelqu'un aurait des infos - conseils pour controller un interrupteur 2 voies?

J'arrive plus ou moins avec la commande on/off qui action l'un des deux relais. Maintenant je ne sais pas comment faire pour l'autre...

**Comment by doudz** [comment]
Un interrupteur est normalement visible comme un switch dans HA, on peut donc utiliser les commandes manuelles depuis l'interface ou les services switch.turn_on, switch.turn_off depuis un automation
S'il y a 2 voies, normalement il devrait y avoir 2 switches

**Comment by letroll** [comment]
merci pour le retour, donc mon problème est plus le fait que je n'ai qu'un périphérique de détecté. Je vais regarder si c'est moi qui l'ai ajouté de travers 👍

**Comment by letroll** [comment]
je confirme que c'était l'association qui avait raté en la faisant à nouveau cela c'est arrangé. Merci !
