### ISSUE TITLE
Aqara vibration set sensitivity

### ISSUE THREAD

**Issue by kbouh320** [doudz/homeassistant-zigate#142]
Hi and than you for the great work, I use the module which is working fine.
Just 1 question about the Aqara vibration sensitivity which I try to change.

According to the doc, i should use the write_attribute service, but I receive some errors back and the sensitivity seems to be the same as before

`RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:718f, sequence:130, lqi:0`

How can I check if the parameter is correclty updated ? Is there a way to read the parameter from the device ?

thank you

**Comment by doudz** [comment]
you have to wake up the device by pushing the small button, without that it won't receive the command

**Comment by kbouh320** [comment]
Indeed, thank you very much
