### ISSUE TITLE
Xiaomi motion sensor

### ISSUE THREAD

**Issue by ALacroix68** [doudz/homeassistant-zigate#150]
Hello,

Je tente d'appairer un capteur de mouvement Xiaomi au plugin.
L'appairage fonctionne correctement, cependant il n'y a aucune information sur l'équipement ni aucun endpoint de listé.

![image](https://user-images.githubusercontent.com/12752363/98033223-7d48c680-1e15-11eb-866e-f6b0b98ff2c2.png)

Est-ce normal ou bien est-ce un problème d'appairage ? (J'ai tenté l'appairage 2 fois, même résultat)

Merci d'avance pour votre aide.

**Comment by csacre** [comment]
Salut,

essaie:
- delete
- redémarré HA
- refait un pairing

**Comment by ALacroix68** [comment]
> Salut,
> 
> essaie:
> 
> * delete
> * redémarre HA
> * refait un pairing

Aussi simple que cela...
Je n'avais très certainement pas redemarré entre le Delete et le Pairing...

Merci beaucoup @csacre !!

**Comment by csacre** [comment]
Avec plaisir...
