### ISSUE TITLE
ZHA à la place de Zigate ??

### ISSUE THREAD

**Issue by vini59fr** [doudz/homeassistant-zigate#155]
Bonjour Doudz

Je viens de voir l'info :( 

Mon Pizigate est en /dev/tty0 et fonctionne sans probleme sous Pizigate
J'ai tenté de migrer vers ZHA, mais dès l'installation de l'integration ,ca ne fonctionne pas (tty0 ou serial0, ca m'indique Impossible de se connecter au périphérique ZHA.)

Desolé de poster du ZHA ici, mais je ne sais pas trop où chercher pour debloquer ma situation (je n'ai pas tout compris avec Zigpy, zigpy-zigate et ZHA)

**Comment by doudz** [comment]
Il faut voir ça comme une bonne nouvelle, l'intégration avec Home Assistant est de meilleur qualité.
Concernant la migration, attention ça ne fonctionne bien qu'avez le firmware 3.1d et HA 0.118

Attention également il n'y a pas de migration entre les 2, il faut donc refaire l'appairage des équipements et comme de nouveaux entities seront créés, il faudra modifier HA en conséquence (tableau de bord, automation , script, etc, etc)

**Comment by doudz** [comment]
Concernant le paramétrage, la pizigate est détecté automatiquement si le chemin est `/dev/ttyAMA0` ou `/dev/serial0` ou `/dev/ttyS0`
Pour tout autre chemin /dev/tty0 par exemple il faut le saisir manuellement sous la forme `pizigate:/dev/tty0`

**Comment by vini59fr** [comment]
ok, merci pour ces infos qui se veulent rassurantes :) 
Je suis bien en HA0.118 et pizigate 3.1d

mais ca coince sur l'installation ZHA
![image](https://user-images.githubusercontent.com/65531566/99687846-68129f80-2a85-11eb-8d06-f0fcd81a6805.png)

**Comment by doudz** [comment]
Il faudrait mettre le log en debug et voir ce qu'il se passe (et éventuellement continuer la discussion ici https://github.com/zigpy/zigpy-zigate)
https://www.home-assistant.io/integrations/zha/#debug-logging

**Comment by doudz** [comment]
Il est important de désactiver l'intégration zigate avant de passer à zha pour ne pas avoir de conflit

**Comment by ruimarinho** [comment]
@doudz do we need to erase PDM for the migration?

**Comment by doudz** [comment]
> @doudz do we need to erase PDM for the migration?

it's not mandatory but since you need to pair devices again, it could be a good thing to start with an empty zigate.

**Comment by MichaelBitard** [comment]
Comment on reset la zigate ? C'est possible depuis la version python ? J'ai l'impression que je peux plus pairer les éléments sous zha car ils sont déjà présents sur le PDM de la zigate.
