### ISSUE TITLE
upgrade pizigate firmware

### ISSUE THREAD

**Issue by maximushugus** [doudz/homeassistant-zigate#158]
Petite question à @doudz 
Je viens de me rendre compte que ma pizigate est encore en firmware 3.1a alors que le dernier est le 3.1d.
Est ce que si j'upgrade avec le service intégré au plug-in je perdrai mes associations de périphériques zigbee et mes paramètres ?
Certains de mes périphériques sont difficiles à appairer et j'aimerais éviter de devoir le refaire.
Merci pour la réponse

**Comment by doudz** [comment]
L'upgrade conserve les associations existantes, il ne sera pas nécessaire de refaire l'appairage.
La procédure d'upgrade va également faire un backup de l'existant qui pourra être rechargé en cas de problème.

**Comment by maximushugus** [comment]
Après la procédure de mise à jour via le service, j'ai bien reçu les notifications de backup et de mise à jour.
Mais ma pizigate est devenue inaccessible : tous mes éléments sont "unavailable".

J'ai essayé de changer le "port" dans ma configuration en suivant ce que j'ai dans hardware sur Hassio.
Voici ce que "hardware" me montre : 

> serial:
>   - /dev/ttyAMA0
>   - /dev/ttyS0

J'ai essayé les 2 sans succès.

![image](https://user-images.githubusercontent.com/36080343/100515273-223b9280-317b-11eb-852f-cba1fcd7d52f.png)
 
Une idée ? 
Merci

**Comment by maximushugus** [comment]
ou bien comment puis je restaurer le .bin de backup qui a été créé lors de la mise à jour ?

**Comment by maximushugus** [comment]
j'ai réussi à restaurer le backup qui avait été crée en 3.1a, et tout refonctionne correctement mais visiblement l'upgrade automatique de 3.1a vers 3.1d ne fonctionne pas

**Comment by doudz** [comment]
Bien joué pour la restauration.
Je vais vérifier la mise à jour, il est possible que la procédure automatique n'utilise pas le bon firmware

**Comment by doudz** [comment]
Je confirme que le service de mise à jour ne téléchargeait pas le bon firmware.
c'est maintenant corrigé, il faut donc mettre à jour le plugin et retenter l'upgrade.
https://github.com/doudz/homeassistant-zigate/commit/327c3e045826afa0be1b175e45d6e1106bd4b2c6

**Comment by maximushugus** [comment]
Merci le service de mise à jour fonctionne maintenant
