### ISSUE TITLE
Fast event do not trigger automation

### ISSUE THREAD

**Issue by doudz** [doudz/homeassistant-zigate#2]
Currently the zigate lib is too fast and sometimes automation is not triggered
for example, the XIAOMI button change his state from on to off then on so fast HA doesn't trigger anything

**Comment by rsokolowski** [comment]
Can you fix this by emitting HA event instead of changing states of sensors ? Using sensor for momentary switch is quite annoying. This is how it is done in deconz and worked for me quite great.

**Comment by doudz** [comment]
This issue is already fix. I have to push the new code
