### ISSUE TITLE
No module named 'zigate'

### ISSUE THREAD

**Issue by ellavas** [doudz/homeassistant-zigate#25]
Hello,,

I want to test your component with HomeAssistant.
I have copied the content of the repo to my custom_components folder.

Then, I have updated my configuration.json with
```
# Enable ZiGate (port will be auto-discovered)
zigate:
  
logger:
  default: error
  logs:
    zigate: debug
    custom_components.zigate: debug
```

But I got an exception at startup:

```
2019-01-23 22:23:06 ERROR (MainThread) [homeassistant.setup] Error during setup of component zigate
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/zigate/__init__.py", line 102, in setup
    import zigate
ModuleNotFoundError: No module named 'zigate'
```

Do you have any idea ?

**Comment by doudz** [comment]
not sure what's going on
Are you sure you did the right thing ?
/config/custom_components/zigate/init.py <= the file init.py is not supposed to exist, it's __init__.py

**Comment by doudz** [comment]
I think you should enable global debug log to see why HA don't install the zigate lib
```
logger:
  default: debug
  logs:
    zigate: debug
    custom_components.zigate: debug
```

**Comment by ellavas** [comment]
Strange issue. The library was well loaded at the next restart.

**Comment by doudz** [comment]
maybe a temporary network problem
