### ISSUE TITLE
Plus de statut "clic maintenu" sur les interrupteur Xiaomi Aqara.

### ISSUE THREAD

**Issue by tomredhot** [doudz/homeassistant-zigate#29]
Salut Doudz
Je viens d'installe la dernière version sur une installation HA neuve (pour essayer de solutionner mon probleme d'hier). J'ai remarqué que maintenant les switchs (double et simple) de Xiaomi ne retourne plus les statuts "wakeup" (pour Double click) "flip_90_81" (pour simple clic) & "shake" (pour clic maintenu) dans HA mais à la place 0, 1 et 2. C'est top, car plus clair.
Cependant, il ne passe plus rien en cas de clic maintenu. 

Merci à toi.
(Désolé, je te fait beaucoup de retour)

**Comment by doudz** [comment]
ah je vois, le clic maintenu c'est justement le 0 normalement mais comme c'est aussi la valeur de retour par défaut ça pose pb... je vais voir ça

**Comment by doudz** [comment]
ça devrait être bon avec la lib 0.27.1

**Comment by tomredhot** [comment]
Parfait! 
Je viens de tester
"" pour aucune action
"1" pour simple clic
"2" pour double clic
"0" pour clic maintenu.
Merci!
