### ISSUE TITLE
[Suggestion] New behaviour for Xiaomi Smart Button (Mijia)

### ISSUE THREAD

**Issue by nerdosity** [doudz/homeassistant-zigate#3]
Brainstorming: in the last days I tried some zigbee implementation, I even flashed a CC2531 to a firmware usable with https://github.com/Koenkk/zigbee2mqtt.
The implementation of MQTT sensor is very good, just the pairing phase is very troublesome, sensors looks like "stubborn" and I spent 10 minutes trying to pair my Mijia button (Aqara devices were added more easily).
Fact is, after the terrible pairing process, the plugin is quite good, and it provides wonderfu informations about the smart button.
I can be a little wrong, I will update this after work when I come back home.

- push and releasing --> send a push
- pushing and keeping pushed --> send a push, then send again the time the button is kept pushed when it is released
- double, triple, quadruple pushing --> send the times the button are quickly pushed and released
- multiple pushing --> send a 128 value, that means nothing but can still be used for automation

**Comment by doudz** [comment]
Be aware that I rely on information provided by zigate, and some information sent by device aren't just not recognized by the zigate firmware (I'm not the zigate vendor)
So supporting new device or new message from device could need a firmware upgrade

**Comment by nerdosity** [comment]
Yes, that's already supported, just behaviour is a little different.
I will provide some screenshot later.

**Comment by nerdosity** [comment]
![image](https://user-images.githubusercontent.com/26657281/43016620-b4ad340e-8c53-11e8-8c03-88c5b70c4d21.png)
What do you think of this behaviour?
It does not provide a released state.
It just provide clics.

I think it's quite nice having the duration of the click.

**Comment by doudz** [comment]
Sure this is nice.
You may push this to Akila, maybe he could change something in the zigate firmware

**Comment by vincentsaluzzo** [comment]
Related to #5 I think

**Comment by doudz** [comment]
Project is now dead, feel free to fork it
