### ISSUE TITLE
What to do once paired

### ISSUE THREAD

**Issue by mbt45** [doudz/homeassistant-zigate#31]
Hi.

I just bought the Zigate and setup you program.
I instantly got the entities to appear thank you, but now I have no idea how to tell Hassio that this one is a switch, this one is a light, etc..., they all appear as entities with no attributes. 
What should I write down once paired?

**Comment by doudz** [comment]
You just have to do ... nothing, eventually just play a little with the device to help the discovery process.
Be aware that at least 2 entities must appear (or more), the first is the zigate entity to display information like battery or last seen, the second and so are classical HA entites like binary_sensor, sensor, light, switch, etc.
What kind of device did you paired ?

**Comment by mbt45** [comment]
Hi
ok I see now switches and temperature, I was only seeing the zigate entities at the end of the list.
Although I still don't see the ikea remote buttons. But I must have not paired it correctly.
For the moment I paired Xiaomi open/cloesed sensor, xiaomi thermometer, ikea lightbulb, ikea motion sensor.
Thank you for the great job.

**Comment by doudz** [comment]
Ikea remote buttons will be available with the next 3.0f firmware

**Comment by mbt45** [comment]
what about the motion detector? It seems not to be seen.

**Comment by doudz** [comment]
If you're talking about the Xiaomi motion detector, it should works out of the box, recognize as a binary sensor, try to push the pair button one time to force the communication

**Comment by mbt45** [comment]
No unfortunately It is IKEA motion detector

**Comment by doudz** [comment]
oh, I don't know how it works, could you provide your zigate.json file ?

**Comment by mbt45** [comment]
where do I get that?

**Comment by doudz** [comment]
A file named zigate.json has been generated in your HA configuration folder

**Comment by cgradl** [comment]
adding the jason and attributes for  Ikea Motion sensor:
```
battery_voltage: 2.8
battery_level: 60
lqi_percent: 33
type: TRADFRI motion sensor
manufacturer: null
receiver_on_when_idle: false
missing: false
generic_type: 
discovery: 
groups: {}
addr: 4422
id: 0
ieee: 90fd9ffffe63692a
last_seen: 2019-02-20 20:46:23
mac_capability: 10000000
power_type: 0
lqi: 84
friendly_name: MotionSensor1
icon: mdi:access-point
```
```
{
            "addr": "4422",
            "discovery": "",
            "endpoints": [
                {
                    "clusters": [
                        {
                            "attributes": [
                                {
                                    "attribute": 5,
                                    "data": "TRADFRI motion sensor",
                                    "name": "type",
                                    "type": "str",
                                    "value": "TRADFRI motion sensor"
                                }
                            ],
                            "cluster": 0
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 32,
                                    "data": 28,
                                    "name": "battery_voltage",
                                    "type": "float",
                                    "value": 2.8
                                },
                                {
                                    "attribute": 33,
                                    "data": 60,
                                    "name": "battery_percent",
                                    "type": "int",
                                    "value": 60
                                }
                            ],
                            "cluster": 1
                        }
                    ],
                    "device": 2128,
                    "endpoint": 1,
                    "in_clusters": [
                        0,
                        1,
                        3,
                        9,
                        2821,
                        4096
                    ],
                    "out_clusters": [
                        3,
                        4,
                        6,
                        25,
                        4096
                    ],
                    "profile": 49246
                }
            ],
            "generictype": "",
            "info": {
                "addr": "4422",
                "id": 0,
                "ieee": "90fd9ffffe63692a",
                "last_seen": "2019-02-20 20:46:23",
                "lqi": 84,
                "mac_capability": "10000000",
                "power_type": 0
            }
        }
```

**Comment by doudz** [comment]
Thanks, I'm not sure but I suppose that sensor works like Ikea remote, so probably supported since firmware 3.0f.
If it's right, you'll have to put zigate and sensor in the same group

**Comment by cgradl** [comment]
Ok will try that. 3.0f firmware is flashed but I have not set any groups so far. I will let you know the outcome.

**Comment by mbt45** [comment]
Hi.

I am traveling away for the next 2 month.

once back I will try and tell you if it worked.

Thank you for your help

**Comment by mbt45** [comment]
Hello

It seem the new update of Hassio killed your Zigate addon.

Any suggestions on how to make it work again?

**Comment by doudz** [comment]
I don't use Hassio so I can't be sure, but I've no problem using HA 0.92.2

**Comment by pdecat** [comment]
I did not face any problem with homeassistant-zigate using Hassio supervisor 162 and HA 0.92.2.

**Comment by mbt45** [comment]
I am a little confused. these are the messages I get

[image: Screenshot 2019-05-08 at 22.12.16.png]

**Comment by cobch** [comment]
@mbt45 @pdecat I have tried to install PiZigate on an RPI running hassio but does not manage to make the configuration with GPIOs in the tutorial below.
https://zigate.fr/documentation/parametrer-la-pizigate/
Does someone can help me to configure Hassio in order to make PiZigate works? The only tutorial I find is for Raspbian )-:

**Comment by doudz** [comment]
Are you on Rpi3 ? if yes, did you disable bluetooth ?
https://github.com/doudz/zigate

**Comment by doudz** [comment]
@mbt45 there's no screenshot....

**Comment by cobch** [comment]
I am on RPI running hassio (I am not running HA on Raspbian). The tutorials on Zigate.fr indicates only how to activate the PiZigate on a Raspbian system (bluetooth deactivation and GPIOs configuration). Could you please update the tutorial for using PiZigate on Hassio? I am pretty new in this "world" and would appreciate more guidance (-:
Thanks a lot for your help.

**Comment by doudz** [comment]
Maybe you could try this :

If you need GPIO on Raspberry Pi 3 for your ~~Z-Wave~~ ZiGate module, add the following line into config.txt (you have to access that on the SD card directly. Simply plug it into your PC and edit it there. The config.txt is not accessible from your Hass.io system, you may need to open the SD card on a Windows or Linux system.):
`
dtoverlay=pi3-miniuart-bt`
