### ISSUE TITLE
Network map problem

### ISSUE THREAD

**Issue by Jsl-1** [doudz/homeassistant-zigate#35]
Hi doudz,

Thank you very much for this feature !
But I have a problem , the png is never generated , because HA always retart before the end of the process. 

I looks like an infinite loop on the same command.

Here are the full log and zigate.json files :
[home-assistant.log](https://file.io/S4n6RO)
[zigate.json](https://file.io/iCV9My)

**Comment by doudz** [comment]
As I said, this feature requires the lib 0.28 which isn't ready yet and graphviz binary
On debian like you have to do something like `sudo apt install graphviz`

**Comment by Jsl-1** [comment]
Ok, 

Sorry, i have not seen your message in the comments before moving my comment to this issue ;)
Will wait for the final ;)

But i think we will have some problem to install graphviz with the hass managed version of HA. will take a look. maybe a json version of the map could be usefull ?

**Comment by jalme** [comment]
If I have to update my docker image this is not going to be possible as the HA docker doesn't permit that (no apt or apt-get). Unless graphviz is distributed as a HA addon this will not work.

**Comment by doudz** [comment]
you're right, I could provide a json file but how render it ? on Jeedom we will use vivagraphjs, is there something like that in HA ?

**Comment by biau** [comment]
You should just provide the output and we can use http://www.webgraphviz.com/
