### ISSUE TITLE
Tradfri: ampoule E27 (1000 lumen)

### ISSUE THREAD

**Issue by kanjusei** [doudz/homeassistant-zigate#37]
Bonjour,  J'ai acheté des ampoules E27 Ikea, j'ai appairé une ampoule avec la zigate ( mis à jour en firmware 3.0 f) .
Je peux allumer et l’éteindre l'ampoule  mais j'ai aucun retour d'état dans Home Assistant, j'ai fais un rafraîchissement de la zigate dans la partie service, mais aucun changement .
J'ai aussi la variation de lumière qui est inversé. (100 vers 0)
[home-assistant.log](https://github.com/doudz/homeassistant-zigate/files/2873349/home-assistant.log)

**Comment by biau** [comment]
J'avais un manque de retour d'état sur un smart plug et c'est un discover_device qui était la solution dans mon cas.

**Comment by kanjusei** [comment]
J'ai essayé le "discover device" mais çà marche pas toujours.
Il ne détecte pas quand l'ampoule est hors ligne ou éteinte. 
Serais ce la faute au firmware?   
J'ai vu sur un post de Doudz, qu'on pouvait mettre à jour les firmwares des ampoules Tradfri  sur la Zigate.

**Comment by doudz** [comment]
Pour que le discover fonctionne il faut que l'ampoule soit sous tension sinon aucune chance que ça fonctionne.
Il est possible de mettre à jour le firmware de certains équipements Ikea effectivement.  
Quel est le modèle des ampoules ?

**Comment by doudz** [comment]
TRADFRI bulb E27 WS opal 1000lm ? Ou TRADFRI bulb E27 opal 1000lm ou autre ?

**Comment by kanjusei** [comment]
Dans les logs de Home assistant,  il me dit que c'est le premier cité.
 Par curiosité, il y a quoi comme différence entre les deux modèles?

**Comment by doudz** [comment]
la version WS doit avoir aussi le contrôle de la température je pense (couleur chaude, froide)

**Comment by kanjusei** [comment]
Oui, j'ai le contrôle de la couleur  de la lumière blanche !!

**Comment by kanjusei** [comment]
Je me suis trompé, c'est la version sans contrôle de la température.
Ces deux versions d'ampoules, peut-on les mettre les a jours par l'intermédiaire de la zigate ?
Est ce normal que l'icône sur Home assistant, quand j'active  le bouton pour éteindre , je ne vois pas visuellement  l'extinction du "toggle"  ? ( Ampoule alimenté électroniquement, je précise)

**Comment by doudz** [comment]
Je suis pas sûr de saisir, si la question est : est-il normal de ne pas voir l'extinction dans HA lorsqu'on coupe l'alimentation de l'ampoule => oui c'est normal puisqu'une fois l'ampoule hors tension elle n'envoie pas l'information à HA, deplus il n'y a actuellement pas de vérification de la présence de l'ampoule sur le réseau.

Par contre si l'ampoule est éteinte "électroniquement" via une commande zigbee (télécommande ou zigate) alors on doit voir également l'extinction dans HA, si ce n'est pas le cas il faut lancer la commande discover_device afin de rétablir la demande de reporting automatique

**Comment by kanjusei** [comment]
Le deuxième cas que tu as cité, j'ai essayé aujourd’hui  la commande "discover_device" alors que l'ampoule est allumé .
Puis j'ai éteint l'ampoule par le bouton de home assistant mais le bouton ne reste pas en off.
