### ISSUE TITLE
Ability to use templates

### ISSUE THREAD

**Issue by pbathuk** [doudz/homeassistant-zigate#48]
The current model seems to be very labour intensive on yourself, however if a template folder & structure could be developed this could remove some of the overhead and give the ability for others to create templates for new devices and upload.
I see on the python version of zigate there is a template structure, so hopefully it is straightforward, maybe not easy, to replicate in the home assistant version...
Happy to discuss and support if I can

**Comment by doudz** [comment]
The purpose of templates is to handle case where discovery fails or is too slow or device need special conf.
Template should be include in the zigate lib.
But during dev, I agree it could be useful to have a use templates dir somewhere

Are you facing problem with a device ? and need a template ?

**Comment by pbathuk** [comment]
Hey, I was having issues with some feibit zigbee plugs, however I have since moved, for the time being, over to deconz to try that out (I have a conbee2 stick). 
I will most likely use the zigate shortly as a second network for outside the range of the current one, so for now it's not a requirement for me. But it might come back again. Cheers
