### ISSUE TITLE
Ajout commande sans fil Legrand

### ISSUE THREAD

**Issue by Adorem** [doudz/homeassistant-zigate#50]
Bonjour Doudz,

Hier soir j'ai essayé d'ajouter [une commande sans fil Legrand](https://www.legrand.fr/pro/catalogue/42559-version-celiane-with-netatmo/commande-sans-fil-celiane-with-netatmo-pour-eclairage-ou-prise-connectee-ou-micromodule-blanc).

La ZiGate et HA l'ont bien détecté. Dans HA j'ai bien une nouvelle entité qui lui correspond :

![image](https://user-images.githubusercontent.com/38832853/57836461-0f43b600-77c1-11e9-9d80-ca33857a9d7a.png)

Par contre HA me dit qu'il faut faire un discovery et je n'ai effectivement pas mes boutons (sensor.zigate_xxx) comme je peux par l'avoir par exemple avec mes commandes Philips Hue.

![image](https://user-images.githubusercontent.com/38832853/57836796-c93b2200-77c1-11e9-8742-7191e89c61c4.png)

Mais quand j'essay de le faire je n'ai que ceci dans les logs de debug probablement parce que le device est sur batterie et donc il n'est pas tout le temps accessible:
```
2019-05-16 10:06:13 DEBUG (SyncWorker_1) [zigate] discover_device 9e2b
```

Si ça peut aider voici les fichiers zigate.json et Remote_switch.json.

[zigate.json.txt](https://github.com/doudz/homeassistant-zigate/files/3186006/zigate.json.txt)
[Remote_switch.json.txt](https://github.com/doudz/homeassistant-zigate/files/3186007/Remote_switch.json.txt)

Merci

**Comment by doudz** [comment]
Bonjour,
D'après ce que je vois l'appareil utilise le cluster 0x000f (15) et l'attribut 0x0055 (85) ce qui est supporté normalement. Pourtant dans le fichier zigate.json on voit que cet attribut n'a pas de nom, comme s'il n'était pas géré.
Est-ce que vous utilisez bien la dernière version de la lib zigate ? (0.29.4)

**Comment by doudz** [comment]
Ok j'ai trouvé le problème, il y a un bug dans la 0.29.4, la gestion du cluster 0x000f n'était pas activé...
Corrigé en 0.29.5

**Comment by Adorem** [comment]
Super vous avez réussi à résoudre mon problème malgré le fait que dans mon premier message j'ai mixé des informations avec un autre module que j'était en train aussi d'ajouter ;-) Je reviendrais d'ailleurs certainement vers vous pour cet autre module.

Là je ne suis pas chez moi donc je ne peux pas tester l'appui sur les boutons mais maintenant j'ai ça qui à été ajouté et donc c'est plutôt bon signe:
![image](https://user-images.githubusercontent.com/38832853/57918127-6ff0f280-7896-11e9-8b08-5abf83b307e8.png)

Je vous confirme le tout ce soir.
Merci pour votre aide !

**Comment by flemzord** [comment]
Salut @adorem 

Tu pourrais décrire comment tu a fait ? 
J’ai essayer de mon côté, mais mon HASS n’arrive pas a voir les interrupteurs sans fils. 

Maxence

**Comment by Adorem** [comment]
Bonjour Maxence,

Je n'utilise plus ce composant mais [zha](https://www.home-assistant.io/integrations/zha/) qui maintenant inclus la zigate.
J'ai changé parce qu'il ne fonctionnait pas correctement mais malheureusement ça ne fonctionne pas mieux avec zha pour moi.
Pour le module Legrand j'avais donc réussi à les intégrés mais je ne me souvient plus exactement ce que j'avais fait.

**Comment by Xavier-M** [comment]
Pour ma part ça fonctionne mais l'ajout est quand même très galère et aléatoire. En gros ça peut prendre plusieurs dizaines de tentatives de presser les différents boutons en appuie court ou long avec la zigate en mode inclusion ou discover device.

Généralement je démonte l'avant (comme pour changer la pile) et du coup on a accès à 3 boutons. Et je tente donc sur tous mais c'est pas très clair.

Dans mon cas je précise que je n'ai pas de passerelle Legrand donc mes interrupteurs n'ont jamais été mis à jour.

Pour finir, dans HASS on ne retrouve pas un interrupteur classique mais juste un sensor "present_value" donc c'est un peu plus compliqué pour l'automatisation mais chez moi ça fonctionne...

**Comment by pipiche38** [comment]
@Xavier-M pour avoir bosser sur ce sujet pour l’intégration sur un autre plugin, j'ai a priori une procédure qui fonctionne à tous les coup.
Il semble du reste que même avec la Box Legrand il y ai des soucis.

Pour faire court, 
(1) appuyer sur le bouton reset le temps qu'il faut pour qu'il passe en rouge, puis relâcher
(2) Alors clicker sur ce bouton environ toutes les secondes jusqu’à ce que la/les Leds passent au vert.

En principe l'appairage est fait et stable dans le temps.

**Comment by Xavier-M** [comment]
@pipiche38 ok, le bouton reset c'est le "troisième" bouton quand tu ouvres l'interrupteur ? Enfin j'ai cru comprendre que tu as l'interrupteur double c'est peut-être autrement.

Mais je confirme aussi qu'une fois que ça marche ça marche très bien. Si on s'en sert pas pendant plusieurs jours alors HASS le met missing mais dès qu'on réutilise ça marche directement sans avoir à rejoin.

**Comment by pipiche38** [comment]
@Xavier-M 

Oui c'est le 3eme bouton sur la droite. Dans le cas du double il est à droite .

Et le comportement que tu décris est correct, l'inter n’émet que si on sans sert (afin de limiter la consommation de batterie)

Et je partage également comme toi, qu'il est plus simple d’ôter la façade afin de mieux contrôler ce que l'on fait lors de l'appairage.

**Comment by pipiche38** [comment]
Xavier 

Par contre je ne peu pas te garantir si le Up/Down est dispo de base ou si il faut avoir associée la commande au hub Legrand pour un upgrade, comme c’est le cas sur l’inter w/o neutre

Envoyé de mon iPhone

**Comment by doudz** [comment]
@Xavier-M a priori c'est géré mais je n'ai pas testé car je n'ai pas l'équipement
ça doit apparaitre dans un fake attribute 0xfff0

**Comment by pipiche38** [comment]
@doudz je ne comprends pas, pourquoi parles-tu de fake attribut ? 
Il s'agit des messages Zigate 0x8085 et 0x8095 qui ont été introduit avec la 3.0f du firmware

**Comment by doudz** [comment]
Dans un souci d'uniformité, dans ma bibliothèque, je gère les messages 0x8085 et 0x8095 comme des messages 0x8102 sur un attribut 0xfff0 qui n'existe pas en réalité

**Comment by pipiche38** [comment]
dans ce cas, il est aussi possible que @Xavier-M n'est pas cela si l'inter sans-fil n'a jamais été mis sur un Hub Legrand et donc il y a de grande chance que par défaut celui-ci ne soit pas activé !
C'est typiquement le cas sur l'inter w/o neutre dont le dimmer est activable uniquement si le firmware a été upgradé, sur la prise connecté la mesure de puissance est elle également dispo, seulement si il y aeu un upgrade Firmware.

Il me semble que @Akila avait mentionné cela, les legrand arrivent avec les fonctions de base, mais activent d'autres fonctionnalité après une première connexion à la box

**Comment by doudz** [comment]
> dans ce cas, il est aussi possible que @Xavier-M n'est pas cela si l'inter sans-fil n'a jamais été mis sur un Hub Legrand et donc il y a de grande chance que par défaut celui-ci ne soit pas activé !
> C'est typiquement le cas sur l'inter w/o neutre dont le dimmer est activable uniquement si le firmware a été upgradé, sur la prise connecté la mesure de puissance est elle également dispo, seulement si il y aeu un upgrade Firmware.
> 
> Il me semble que @akila avait mentionné cela, les legrand arrivent avec les fonctions de base, mais activent d'autres fonctionnalité après une première connexion à la box

@pipiche38 existe-t-il une mise à jour OTA quelques part ? comme pour Ikea ? on pourrait imaginer mettre à jour les équipements sans la box Legrand

**Comment by doudz** [comment]
si qqn a une box, peut-être qu'on peut sniffer le traffic réseau et trouver le serveur de fichier OTA

**Comment by pipiche38** [comment]
@doudz @Xavier-M ,

Voila ce que j'apprécie avec Ikea/Tradfri

Pour ce qui est de Legrand/Netatmo  j'imagine que le serveur OTA est dans leur Cloud.

**Comment by pipiche38** [comment]
@Xavier-M par rapport à ta question sur Present  Value, je suppose que tu fais référence à l’attribut 0x0055 du cluster 0x000f.

A priori cet attribut est utilisé pour le On/Off, par contre pour le Level Control là il passe par le message 0x8085

Je viens de faire le test sur une Telecommande de Volet et là c'est la meme chose, il utilise le present value pour le Open et Close

**Comment by Xavier-M** [comment]
Je parle bien de cet attribut pour le On/Off et j'ai bien l'impression que je ne reçois jamais rien concernant le Level Control. J'en ai pas vraiment besoin mais un jour peut-être que je prendrai une passerelle pour maj ;)

**Comment by pipiche38** [comment]
As-tu essayer de faire un bind des cluster 0x0006 et 0x0008 

Envoyé de mon iPhone
