### ISSUE TITLE
Zigate almost unusable after latest update

### ISSUE THREAD

**Issue by nerdosity** [doudz/homeassistant-zigate#56]
Hi, yesterday I updated your module after some time. 
Everything went crazy: a lot of delay for turning on/off lights, almost no Xiaomi sensors working, and it even slowed down Home Assistant.

https://termbin.com/cw2g

BTW: status are unsynced on almost every light. WiFi lights are working good, Zigbee lights are now a mess, almost none light/outlet synced with Home Assistant status (and discovery / refresh doesn't work anymore).

**Comment by biau** [comment]
Try to rollback to version  0.29.x
It looks like an issue with the new state polling policy introduced in 0.30

**Comment by nerdosity** [comment]
I reverted all polling but climate. 
No effect, my configuration stay unusable.
It seems that light are synced for a while after HA restart, then they go out of sync. 
It just happens with zigbee lights, WiFi ones like Yeelights are solid.

**Comment by doudz** [comment]
I think the current polling is too agressive, I will try to make it more smart

**Comment by nerdosity** [comment]
It seems much better with latest version.
It just seems a little slower to react to commands, but at least I didn't lose all devices control after few hours

**Comment by doudz** [comment]
Recent changes are :
Polling every 60sec instead of 30sec
Polling only ask for pertinent attribute
When turn on/off, assume the state without waiting polling

Polling is needed when some devices don't report their state automatically and when the state can change outside of HA, like a wall switch for example

If you have a lot of switch, the system could be slow, maybe 60sec is too agressive
I planned to implement polling in the zigate lib instead of using HA to have a better control

**Comment by Jsl-1** [comment]
Hi @doudz,

If you do that in zigate lib, can we have a parameter to disable polling ?

**Comment by doudz** [comment]
why not

> Hi @doudz,
> 
> If you do that in zigate lib, can we have a parameter to disable polling ?

**Comment by Jsl-1** [comment]
Would be great!
If you want, I will make a PR to make this option available at homeassistant-zigate side. I will do it for me anyway.

**Comment by doudz** [comment]
> Would be great!
> If you want, I will make a PR to make this option available at homeassistant-zigate side. I will do it for me anyway.

yes, any contribution is appreciate :smile:
