### ISSUE TITLE
zigate.climate error: SUPPORT_AWAY_MODE

### ISSUE THREAD

**Issue by b0kar** [doudz/homeassistant-zigate#59]
Hello,

I have an error in the logs after HA boots:
`2019-07-24 15:58:57 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform zigate.climate: Platform not found (cannot import name 'SUPPORT_AWAY_MODE' from 'homeassistant.components.climate.const' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/climate/const.py)).`

I don't know if it's related to an HA upate or a zigate update
Begun with HA 0.95 and still present with HA 0.96

b0kar

**Comment by doudz** [comment]
you're right, climate platform has changed with HA 0.95, I have to fix that

**Comment by doudz** [comment]
Should be ok now, could you give a try ?

**Comment by b0kar** [comment]
Problem solved.
Thx for your reactivity
