### ISSUE TITLE
[Suggestion] Ability to permit-join without calling service manually

### ISSUE THREAD

**Issue by vincentsaluzzo** [doudz/homeassistant-zigate#6]
The title is explicit, I think it would be more user friendly for common user if we don't need to use developer tool to permit join

I think the use of Configuration > Integration like for deCONZ would be the better choice.

**Comment by doudz** [comment]
I would be nice ! Any help will be appreciated

**Comment by vincentsaluzzo** [comment]
I'm already worked on it, but for that I need to be able to analyse return of ZiGate after a permit_join.

To do this, I think to create a listener and make a `is_permitting_join()` on this timer to have the current state, and depending on the previous one, fire a event `zigate_permit_join_started` or `zigate_permit_join_ended` on the event bus.

It's work but I've encount some problems, sometimes ZiGate got disconnected, sometimes it's ok so I need to investigate a little bit more on that point .

**Comment by vincentsaluzzo** [comment]
Ok, so I can't continue on this without the integration of this components to HA it self, because using of "components" integration in config entry need to change code in HA it self:

```
Temporarily, all config flow handlers will also need to add their component name to the FLOWS constant in homeassistant/config_entries.py. We are working on automating discovery.
```

*from https://developers.home-assistant.io/docs/en/config_entries_config_flow_handler.html*

**Comment by doudz** [comment]
Project is now dead, feel free to fork it
