### ISSUE TITLE
added IKEA TRADFRI_bulb_GU10_W_400lm support

### ISSUE THREAD

**Issue by iron91770** [doudz/homeassistant-zigate#65]
Hello

I have IKEA GU10 bulbs that are recognized by the zigate and I have no command for the drivers. When I try to discover, I get the following message:

No template found for TRADFRI_bulb_GU10_W_400lm

**Comment by iron91770** [comment]
zigate.json:

       {
            "addr": "81df",
            "discovery": "auto-discovered",
            "endpoints": [
                {
                    "clusters": [
                        {
                            "attributes": [
                                {
                                    "attribute": 4,
                                    "data": "IKEA of Sweden",
                                    "name": "manufacturer",
                                    "value": "IKEA of Sweden"
                                },
                                {
                                    "attribute": 5,
                                    "data": "TRADFRI bulb GU10 W 400lm",
                                    "name": "type",
                                    "type": "str",
                                    "value": "TRADFRI bulb GU10 W 400lm"
                                },
                                {
                                    "attribute": 0,
                                    "name": "zcl_version",
                                    "value": null
                                },
                                {
                                    "attribute": 1,
                                    "name": "application_version",
                                    "value": null
                                },
                                {
                                    "attribute": 2,
                                    "name": "stack_version",
                                    "value": null
                                },
                                {
                                    "attribute": 3,
                                    "name": "hardware_version",
                                    "value": null
                                }
                            ],
                            "cluster": 0
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0
                                },
                                {
                                    "attribute": 65533
                                }
                            ],
                            "cluster": 3
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0
                                },
                                {
                                    "attribute": 65533
                                }
                            ],
                            "cluster": 4
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0
                                },
                                {
                                    "attribute": 1
                                },
                                {
                                    "attribute": 2
                                },
                                {
                                    "attribute": 3
                                },
                                {
                                    "attribute": 4
                                }
                            ],
                            "cluster": 5
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0,
                                    "name": "onoff",
                                    "type": "bool",
                                    "value": false
                                },
                                {
                                    "attribute": 16384
                                },
                                {
                                    "attribute": 16385
                                },
                                {
                                    "attribute": 16386
                                },
                                {
                                    "attribute": 16387
                                }
                            ],
                            "cluster": 6
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0,
                                    "name": "current_level",
                                    "type": "int",
                                    "value": 0
                                },
                                {
                                    "attribute": 1
                                },
                                {
                                    "attribute": 15
                                },
                                {
                                    "attribute": 16
                                },
                                {
                                    "attribute": 17
                                }
                            ],
                            "cluster": 8
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0
                                },
                                {
                                    "attribute": 256
                                },
                                {
                                    "attribute": 257
                                },
                                {
                                    "attribute": 262
                                },
                                {
                                    "attribute": 263
                                }
                            ],
                            "cluster": 2821
                        }
                    ],
                    "device": 256,
                    "endpoint": 1,
                    "in_clusters": [
                        0,
                        3,
                        4,
                        5,
                        6,
                        8,
                        2821,
                        4096
                    ],
                    "out_clusters": [
                        5,
                        25,
                        32,
                        4096
                    ],
                    "profile": 49246
                }
            ],
            "generictype": "",
            "info": {
                "addr": "81df",
                "ieee": "d0cf5efffeda82f6",
                "last_seen": "2019-08-01 22:11:55",
                "lqi": 114,
                "mac_capability": "10001110"
            }
        },

**Comment by iron91770** [comment]
thanks to the raw command, I was able to force the discovery of the cluster and that corrected my problem.

**Comment by slouies** [comment]
Hi,
I have the same issue.
Can you tell me which comment you sent ?

**Comment by doudz** [comment]
You should be able to call the service zigate.discover_device from dev tab

**Comment by slouies** [comment]
Yes, I know, but It returns the same message as iron91770: 
"No template found for TRADFRI_bulb_GU10_W_400lm"
And there are no command at all for the bulb in the States panel.
I can turn on and off the bulb by scripts, and control the brightness as well (but I have to do it with raw_command with, for instance data={"cmd":"0x0081", "data": "0268ea010101780064"}).
Is that normal ?
Sorry, I started with HASS (and obviously the ziagte) only a few weeks ago.
Not sure about what is normal and what's not :-)

**Comment by doudz** [comment]
You should try the command 0x0043 , maybe it would help

**Comment by slouies** [comment]
Sorry, but the command does not show any effect :-(

**Comment by doudz** [comment]
you should update to last release

**Comment by slouies** [comment]
Did that and quickly launched discover_device.
Looks like it's working ! 
Further investigations this evening !
Thanks for all !
