### ISSUE TITLE
device

### ISSUE THREAD

**Issue by foXaCe** [doudz/homeassistant-zigate#68]
bonjour,

a chaque démarrage j'ai ce message.

The ZiGate device 00158d0002c8c02d(1505) needs to be discovered (missing important information)

je dois faire quoi ?

**Comment by doudz** [comment]
Il s'agit de quel type d'équipement ?
Il faudrait appeler le service discover sur cette équipement (et penser à réveiller l'équipement s'il fonctionne sur pile en appuyant qq fois sur le bouton d'appairage)
ou éventuellement refaire l'appairage car la découverte est faite automatiquement après l'appairage

**Comment by foXaCe** [comment]
Bonjour,

il s'agit de sensor xiaomi, effectivement sur pile.
Comment j'appel le service discover ?

**Comment by doudz** [comment]
Via => Outils de développement  => Services

![image](https://user-images.githubusercontent.com/1262548/63646828-262b6a00-c719-11e9-8412-6e002a4e9491.png)
![image](https://user-images.githubusercontent.com/1262548/63646833-33e0ef80-c719-11e9-8d2c-0f826d75f9f7.png)

**Comment by foXaCe** [comment]
ok je vais tester, j'avais fait l'appairage sur mon pc , je sais pas si cela change quelque chose

**Comment by doudz** [comment]
Oui c'est pour ça, l'appairage c'est une chose mais pour un bon fonctionnement le plugin a besoin de connaitre d'autres information, peut-être qu'il ne manque que le type,  si c'est le cas pas besoin de faire tout ça, juste une impulsion sur le bouton d'appairage va suffire car les capteurs Xiaomi envoient cette info lorsqu'on appui sur le bouton

**Comment by foXaCe** [comment]
ok merci , quand je rentre chez moi je test ça et je vous tiens au courant. merci beaucoup pour votre aide

**Comment by foXaCe** [comment]
nickel ca marche super, j'ai refait les permit join depuis Hass . tout marche sans souci maintenant.
bravo
