### ISSUE TITLE
New device not automatically added to list

### ISSUE THREAD

**Issue by vincentsaluzzo** [doudz/homeassistant-zigate#7]
When a successfully added a new device, I receive the appropriate notification in the home but the zigate panel don't show it in his list and the activity handle by this object will not visible in HA without restarting it

**Comment by doudz** [comment]
Yes you're right.
But you don't need to restart HA, just change the state of your device (eg for a door sensor, open the door)
The device will appear as soon as the state change

**Comment by vincentsaluzzo** [comment]
Mh, I'm not sure about that solution because i've tested it yesterday but I will retry next time to be sure

**Comment by doudz** [comment]
I think I have just fix it

**Comment by doudz** [comment]
Project is now dead, feel free to fork it
