### ISSUE TITLE
Startup is too slow

### ISSUE THREAD

**Issue by doudz** [doudz/homeassistant-zigate#8]
Startup is too slow
try to use async

**Comment by vincentsaluzzo** [comment]
By using a components and because ZiGate could be in WiFi, I think you should considering to add async discovery of Zigate and integrate it in Components no ? 

By this way, you must considering to use `async_setup`

**Comment by doudz** [comment]
Yes, this is the good way

**Comment by doudz** [comment]
Project is now dead, feel free to fork it
