### ISSUE TITLE
light issue with latest version

### ISSUE THREAD

**Issue by biau** [doudz/homeassistant-zigate#83]
Hi @doudz ,
Latest version is kind of broken for me.
Now I have to click two time to turn on/off a light.
Please find the logs when I turn on/ off light 5f06 multiple times:
https://termbin.com/74f9

At first after a restart I can turn the light on using the gui.
Then if I try to turn it off I can see the lovelace entity turning off but back on in the next moment.
And after that I can click to turn it off and it works.
Same issue when I try to turn if on again.

**Comment by doudz** [comment]
Could you try to replace transition = 1 by transition = 0 in light.py ?
https://github.com/doudz/homeassistant-zigate/blob/master/custom_components/zigate/light.py#L170
https://github.com/doudz/homeassistant-zigate/blob/master/custom_components/zigate/light.py#L205
https://github.com/doudz/homeassistant-zigate/blob/master/custom_components/zigate/light.py#L217

**Comment by biau** [comment]
Yes that's it.
Sorry I have seen that commit but to be honnest I've quickly reverted to older version as soon as people in the house were complaining about light issues.
