### ISSUE TITLE
Position volet inter legrand

### ISSUE THREAD

**Issue by oopsyss** [doudz/homeassistant-zigate#84]
Bonjour

J'ai installer un interrupteur connecté Legrand sur mon système
-Raspbian Buster
-home assistant 0.102
-zigate 3.1a

Il est reconnu et il fonctionne bien.
Je souhaite connaitre la position de mon volet roulant.
Cela est il possible?
Le champs "current_position" semble renvoyer l'état de la dernière commande.
current_position: 0= mode down
current_position: 50 = mode stop
current_position: 100= mode up

merci de votre aide

**Comment by doudz** [comment]
Ce n'est pas possible, pour la simple raison que la position n'est pas connue, il n'y a pas de retour d'information entre le volet et l'interrupteur.
L'interrupteur permet simplement de controller la montée ou la descente
