### ISSUE TITLE
Support SonOff BASICZBR3

### ISSUE THREAD

**Issue by iron91770** [doudz/homeassistant-zigate#91]
Hello,
I just bought a BASICZBR3 sonoff switch. Hassio detects the switch well with its state but I cannot order it.

Would it be possible to take it over. Here is the content of my zigate.json

{
            "addr": "f48b",
            "discovery": "auto-discovered",
            "endpoints": [
                {
                    "clusters": [
                        {
                            "attributes": [
                                {
                                    "attribute": 4,
                                    "data": "SONOFF",
                                    "name": "manufacturer",
                                    "value": "SONOFF"
                                },
                                {
                                    "attribute": 5,
                                    "data": "BASICZBR3",
                                    "name": "type",
                                    "type": "str",
                                    "value": "BASICZBR3"
                                }
                            ],
                            "cluster": 0
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0,
                                    "data": false,
                                    "name": "onoff",
                                    "type": "bool",
                                    "value": false
                                }
                            ],
                            "cluster": 6
                        }
                    ],
                    "device": 9,
                    "endpoint": 1,
                    "in_clusters": [
                        0,
                        3,
                        4,
                        5,
                        6
                    ],
                    "out_clusters": [
                        0
                    ],
                    "profile": 260
                }
            ],
            "generictype": "",
            "info": {
                "addr": "f48b",
                "bit_field": "0100000000000001",
                "descriptor_capability": "00000000",
                "id": 49,
                "ieee": "00124b001e721d02",
                "last_seen": "2020-01-01 13:04:00",
                "lqi": 75,
                "mac_capability": "10001110",
                "manufacturer_code": "0000",
                "max_buffer": 80,
                "max_rx": 160,
                "max_tx": 160,
                "power_type": 1,
                "server_mask": 0
            }
        }

**Comment by doudz** [comment]
https://github.com/doudz/zigate/issues/158

**Comment by iron91770** [comment]
thank you very much that solved my problem well. Do you plan to incorporate this change with your next update?

**Comment by MichaelBitard** [comment]
These are supported quite well, thanks!

However I have this in my logs:
`2020-04-13 10:24:07 INFO (ZiGate-Decode data) [zigate] No template found for BASICZBR3`, I don't know if there is anything I can do to help you.

The problem remaining is that for each of these devices, I have a switch and a binary_sensor associated, but the binary_sensor is never updated. It could be really handy if it worked because sometimes when I toggle on or off a component, it does not switch on or off and I have to relaunch the same command, which I could automate if I had the binary_sensor working.
