### ISSUE TITLE
Startup KO avec H.A 0.104

### ISSUE THREAD

**Issue by b0kar** [doudz/homeassistant-zigate#93]
Hello Doudz,

zigate installé via HACS et à jour (8e3e80b)
Le component ne démarre pas.
`2020-01-15 23:19:27 ERROR (MainThread) [homeassistant.setup] Error during setup of component zigate
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/zigate/__init__.py", line 288, in setup
    component = EntityComponent(_LOGGER, DOMAIN, hass, scan_interval, GROUP_NAME_ALL_ZIGATE)
TypeError: __init__() takes from 4 to 5 positional arguments but 6 were given`

Ca pourrait être lié au breaking change concernant les groupes?

Rollback pour ceux qui utilisent les venv
```
sudo systemctl stop home-assistant@homeassistant.service
sudo -u homeassistant -H /bin/bash
source /srv/homeassistant/bin/activate
pip3 install homeassistant==0.103.6
deactivate
exit
sudo systemctl start home-assistant@homeassistant.service
```

b0kar

**Comment by barcelona92** [comment]
> Hello Doudz,
> 
> zigate installé via HACS et à jour ([8e3e80b](https://github.com/doudz/homeassistant-zigate/commit/8e3e80b6b47650765943b0489ad0d5d05d9ea08b))
> Le component ne démarre pas.
> `2020-01-15 23:19:27 ERROR (MainThread) [homeassistant.setup] Error during setup of component zigate Traceback (most recent call last): File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 174, in _async_setup_component component.setup, hass, processed_config # type: ignore File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/home/homeassistant/.homeassistant/custom_components/zigate/__init__.py", line 288, in setup component = EntityComponent(_LOGGER, DOMAIN, hass, scan_interval, GROUP_NAME_ALL_ZIGATE) TypeError: __init__() takes from 4 to 5 positional arguments but 6 were given`
> 
> Ca pourrait être lié au breaking change concernant les groupes?
> 
> nicobouc

Yes in the new version 0.104 the Zigate is KO not start... please any idea?? alls zigbee devices are ko :-(

**Comment by arkpoah** [comment]
It's due to changes with groups : 
https://www.home-assistant.io/blog/2020/01/15/release-104/#reload-all-the-input-things--bye-generated-groups

group_name parameter has been removed in EntityComponent method :
https://github.com/home-assistant/home-assistant/blob/master//homeassistant/helpers/entity_component.py#L64
